## Basics

As with the `matplotlib` reference notebook, this should not be a substitute for the documentation: https://numpy.org/doc/stable/

If you are unsure of how to do something using `numpy` the documentation is the single best reference out there.

To summarize part of the introduction page of the docs, `numpy` is mainly an implementation of a fast n-dimensional array data structure. It is fast because when you call `numpy` functions, you are calling optimized C or C++ code rather than iteratively feeding text into the Python interpreter.

As we will illustrate in this notebook, this can be very powerful as a computational tool.

In [2]:
import numpy as np

We will start by creating a simple array. The `numpy.array` function can create arrays from lists and other iterable Python objects.

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

While you can still use Python's built-in `len` function, it will by default return the length of the first dimension of the array. Our array only has 1 dimension but when you are working with $n$-dimensional arrays, it is often more useful to use the `shape` property to access this information as a tuple.

In [4]:
len(arr)

10

In [11]:
arr.size  # number of elements (product of all shapes)

10

In [5]:
arr.shape

(10,)

In [10]:
arr.shape[0] == len(arr) == arr.size

True

In [9]:
arr.shape == len(arr)  # note that shape is always a tuple!

False

## Array Arithmetic

Arrays can be treated like scalar variables in many ways. Nearly all of Python's built-in arithmetic will work element-wise on arrays.

### Array-Scalar Operations

In [5]:
arr + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [8]:
arr % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

### Array-Array Operations

If arrays are the same shape, we can combine their elements using arithmetic as well.

In [32]:
a = np.array([2, 3, 4, 5, 6, 7, 8, 9])
b = np.ones_like(a)  # or np.ones(a.size) or np.ones(a.shape[0]) or np.ones(len(a))

In [33]:
a + b

array([ 3,  4,  5,  6,  7,  8,  9, 10])

Note that Python order of operations still applies.

In [34]:
a + b / b - a

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
(a + b) / (a - b)

array([3.        , 2.        , 1.66666667, 1.5       , 1.4       ,
       1.33333333, 1.28571429, 1.25      ])

In [37]:
a + (b / a) - b

array([1.5       , 2.33333333, 3.25      , 4.2       , 5.16666667,
       6.14285714, 7.125     , 8.11111111])

## Boolean Arrays and Masking

One of the most useful tools in `numpy` is the ability to define boolean arrays. These can be used to mask out certain elements of arrays based on conditions.
We will start with a pre-defined boolean array to illustrate how it can be used, then we will show how to construct different boolean arrays.

In [39]:
mask = np.array([True, True, False, False])

In [43]:
arr = np.arange(mask.size)
arr

array([0, 1, 2, 3])

If we feed the boolean array as an index to another array, it gives us a view of only the `True` elements.

In [44]:
arr[mask]

array([0, 1])

We can use this view to assign values to only certain elements of our array.

In [45]:
arr[mask] = -1
arr

array([-1, -1,  2,  3])

We can define boolean arrays in terms of conditions. For example let's extract all even numbers from an array

In [12]:
arr = np.arange(20)
even = (arr % 2) == 0
arr[even]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Boolean operations on boolean arrays

Boolean arrays can be modified using basic boolean operations such as AND (`&`), OR (`|`), XOR (`^`), and NOT (`~`)

In [19]:
even = (arr % 2) == 0
odd = ~even
arr[odd]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
arr[even & odd]

array([], dtype=int32)

In [21]:
arr[even | odd]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Indexing arrays

Similar to boolean arrays, we can define arrays of indices that we can feed into another array to access specific values.

In [22]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
idxs = np.array([0, 1, 2])

In [18]:
arr[idxs]

array([0, 1, 2])